### ISSUE TITLE
B310s-927 how to read flash 

### ISSUE THREAD

**Issue by karim1630** [forth32/balongflash#11]
I need now how to read flash from b310s-927whit balong-flash or cmd i have one b310s-927 dead whit flash frim b310s-927 swver:21.311.05.00.1269 i have not fined this frim i like now how to read it pl thenks

**Comment by chipoza** [comment]
i can ok this device .u can done through boot point.and after this loader you flash through flasher v2.0 or huawei hiscilicon flasher.

**Comment by karim1630** [comment]
But i like now if i can read flash form one live

Télécharger Outlook pour Android<https://aka.ms/ghei36>



On Fri, Dec 2, 2016 at 6:17 PM +0100, "chipoza" <notifications@github.com<mailto:notifications@github.com>> wrote:


i can ok this device .u can done through boot point.and after this loader you flash through flasher v2.0 or huawei hiscilicon flasher.

-

**Comment by karim1630** [comment]
How to flash bin frim whit  flasher v2.0

Télécharger Outlook pour Android<https://aka.ms/ghei36>



On Fri, Dec 2, 2016 at 6:17 PM +0100, "chipoza" <notifications@github.com<mailto:notifications@github.com>> wrote:


i can ok this device .u can done through boot point.and after this loader you flash through flasher v2.0 or huawei hiscilicon flasher.

-

**Comment by faridmay** [comment]
hi .i have same probleme with this modem b310s927 only led power switch.i do many step but not solution
and  How to flash bin frim whith  flasher v2.0

**Comment by karim1630** [comment]
I have same probleme whit this modem b310s-927

**Comment by faridmay** [comment]
I've experimented with updated several times but there is no positive result

**Comment by karim1630** [comment]
My modem b310s-927 is protect whit this frim 21.300.01.00.1269 i dont were i can fine this frim now is dead i do not now how to revive it if you can help mi pl

**Comment by faridmay** [comment]
led power  actuation or not

**Comment by karim1630** [comment]
Yes led power only

**Comment by karim1630** [comment]
I have tested meny frim but still in led power

**Comment by faridmay** [comment]
same probleme

**Comment by karim1630** [comment]
Ah ok  like mi

**Comment by faridmay** [comment]
i do not have solution for this probleme

**Comment by karim1630** [comment]
You are from were

**Comment by faridmay** [comment]
algerian

**Comment by karim1630** [comment]
What do use to flash this modem program

**Comment by faridmay** [comment]
balong usb flash and balong flash with cmd

**Comment by karim1630** [comment]
Ah ok i use same like you end whit huawie hisilicon frim writer

**Comment by faridmay** [comment]
and Huawei_Flasher_v2 is read modem
swver:21.180.99.01.00
isover:WEBUI_17.100.08.01.983
productname:BV7R11C
dloadtype:1

IMEI: 123456789123456

**Comment by karim1630** [comment]
Do you have skype

**Comment by faridmay** [comment]
yes faridmay

**Comment by karim1630** [comment]
Ok i have send invitation

**Comment by faridmay** [comment]
ok

**Comment by karim1630** [comment]
halim20042

**Comment by AhmedAmmarNegoudi** [comment]
hello guys i'm too from algeria 
did you find any solution ?

**Comment by karim1630** [comment]
not yet pro

**Comment by AhmedAmmarNegoudi** [comment]
guys try this steps it dosn't work for me (i think that's my modem is breaked permenently)
but you can try it in your own risk
open device manager verify wich port is HUAWEI Mobile Connect - 3G PC UI Interface
for example you find it com15
open cmd go to path where you put balong_flash.exe put the firmware that you want to flash it in the same path (ex: B310s-927_Update_21.110.99.02.00_Universal.BIN)
then write this command in cmd 
balong_flash.exe -g0 -p15 B310s-927_Update_21.110.99.02.00_Universal.BIN
wait until progam finishs laoding and that's it you should now have an alive modem

**Comment by faridmay** [comment]
same probleme. stay in led power

**Comment by karim1630** [comment]
same to mi probleme. stay in led power

**Comment by karim1630** [comment]
This modem of algeria telcom is protecred  end i have try a lot frim end stil dead

**Comment by AhmedAmmarNegoudi** [comment]
Thanks God finaly my routrer back to life 
and there the solution guys for algerian users with Algerie Telecom router:
1-Load ubsloader-310.BIN with balong usbload or BalongUSBDownloader
2-Download firmware of b315 from this link :
http://www.mediafire.com/file/371hp9w4j9veb3f/B315s-936_Zain.zip
extract files then run go_hdlc.exe
then run Huawei_flasher 
select HUAWEI Mobile Connect - 3G PC UI Interface COM Port
Click flash button and browse to 936_Zain.hmf select it and start flashing
your router may lose imei SN but it is easy to slove it 
i hope this will help you brothers 
wa essalamou al3ikom

**Comment by karim1630** [comment]
I will tray it my frend thenks

**Comment by AhmedAmmarNegoudi** [comment]
does it work for you bro ?

**Comment by karim1630** [comment]
No  not work for mi

**Comment by red1980** [comment]
hello
ou are from oran ?

**Comment by SULEMANAKAZI** [comment]
AhmedAmmarNegoudi can you plz help me my i dont know how to write bin file

**Comment by SULEMANAKAZI** [comment]
HJello Karim1630

**Comment by sdjali** [comment]
Dear  AhmedAmmarNegoudi  

i have followed your method ant it works for me , but i need the firmware for this model B310s-927

**Comment by AhmedAmmarNegoudi** [comment]
ok man 
if you don't find the b310s-927 firmaware yet this is the methode
first download any firmeware for b310s-927 in .bin format
change the extension of firemware to .exe
then download this soft  
http://www.mediafire.com/file/e44889od2mbwtk7/Huawei_Flasher.exe
open it then go to select firmware browse to your .exe firmware
you will get a new folder named by firmware name 
this folder contains 10 or 11 .bin files and 1 .hmf file ok 
open the .hmf file it will be like this for example
***********************************************
Found Firmware for: 33 v31        

01.bin 00110000 0002EA3E
02.bin 00200000 000011AE
03.bin 00010000 00000800
04.bin 00090000 00595ACB
05.bin 00220000 00A0E39A
06.bin 00230000 0000B768
07.bin 00240000 0024527C
08.bin 00250000 0022E845
09.bin 00590000 019D0E00
10.bin 005A0000 0092E400
11.bin 005B0000 008DCE00
**************************************** 
delete all lines that don't contain  .bin an hexadecimal values to get your file like this 
*************************************************
01.bin 00110000 0002EA3E
02.bin 00200000 000011AE
03.bin 00010000 00000800
04.bin 00090000 00595ACB
05.bin 00220000 00A0E39A
06.bin 00230000 0000B768
07.bin 00240000 0024527C
08.bin 00250000 0022E845
09.bin 00590000 019D0E00
10.bin 005A0000 0092E400
11.bin 005B0000 008DCE00
************************************************
ok now you have a compatible firmware you can replace the b315s firmware by it
i hope it helps you and i'm sorry for my bad english

**Comment by sdjali** [comment]
dear man

thanks very much for your support , i have followed the steps and it works
for me , thanks a lot again.

On Mon, Mar 27, 2017 at 3:27 PM, AhmedAmmarNegoudi <notifications@github.com

**Comment by AhmedAmmarNegoudi** [comment]
nevermind man your are welcome 
i'm happy because this helped you !

**Comment by tanveerahmad6506** [comment]
Huawei_Flasher_v2 plz link

**Comment by tanveerahmad6506** [comment]
Huawei_Flasher_v2 link plz

**Comment by AhmedAmmarNegoudi** [comment]
that's it man 
http://www.mediafire.com/file/b8ac62fjar2bftz/Huawei_Flasher_v2.rar

**Comment by intikman** [comment]
Hi !

Please "sdjali" Can I have a firmware please for this model B310s-927

**Comment by sdjali** [comment]
hi

here it is ​
 B310s-927_UPDATE_21.300.01.00.00.rar
<https://drive.google.com/file/d/0B_wYjXPcTwMfUGZmUGJ2eGJzWUk/view?usp=drive_web>
​

**Comment by intikman** [comment]
Thank U sdjali , I'll try it than I'll report here

**Comment by intikman** [comment]
Sorry sdjali , I need firmware can use it with HUAWEI FLASHER, bexause I bricked my modem 
Thank'  a lot

**Comment by sdjali** [comment]
ok try this ​
 B310s-927_UPDATE_21.300.01.00.00.rar
<https://drive.google.com/file/d/0B_wYjXPcTwMfTDl1SlRpeDVQcEk/view?usp=drive_web>
​

**Comment by karim1630** [comment]
Hi frend my new skype karim16302

**Comment by sdjali** [comment]
hi karim how can i help you ??

**Comment by kounzo** [comment]
how can i downgrade new firmware with cutomization on b310? i tried boot point but modem doesnt power up, USB detect but no com port assigned.

**Comment by g502** [comment]
My b310 customerise with airtel india it is dead ,i boot shot and flash with boot loader it starts also showing led i tried many times with huwei flasher but after 3 files download stopped and not respond huwei flasher .i also tries to untick 3files and others files go successfully but nothing happen it gone to no light.any supported fw or cmd solution suggust me.

**Comment by chipoza** [comment]
Change window

**Comment by saqi755** [comment]
Sir i need usbloader for E5573s-322 i tried allavailable firmwares but still notworking

**Comment by saqi755** [comment]
Firmware Version installed 21.321

**Comment by SandeepHar** [comment]
i Upgraded my my b310s-927 to B310s-927_UPDATE_21.316.01.00.1304 after completion it is not accepting any sim card, also usb disabled Now i am  unable to upgrade or downgrade!! anyone know what happened to this!!

**Comment by sdjali** [comment]
Hello ... first you tell us from which version you upgrade it then the way
you upgrade it (I mean the software you used )for the usb you cannot use it
with versio 21.316.... you need to downgrade to universal version to use it
.... then check your imei if it become all 0000 or it is still the same

On May 5, 2017 4:56 PM, "SandeepHar" <notifications@github.com> wrote:

i Upgraded my my b310s-927 to B310s-927_UPDATE_21.316.01.00.1304 after
completion it is not accepting any sim card, also usb disabled Now i am
unable to upgrade or downgrade!! anyone know what happened to this!!

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/forth32/balongflash/issues/11#issuecomment-299503714>,
or mute the thread

**Comment by SandeepHar** [comment]
Thaks for your reply! I upgraded from 21.311 using multicast along with dc unlocker to send the at commant to reset the modem , at that point usb was working. Now im unable to downgrade. i tried to downgrade through multicast but it did't happen. Is there any way to downgrade. My device became useless after this.!!

**Comment by sdjali** [comment]
You are welcome in fact my internet is cut untill tomorrow I am using only
my mobile so I cannt upload ths softfor you but suggest to follow one vedio
in youtube it can help you .... unlock Nck Tutorial for huawei B310-22
922,927 B315.mp4

**Comment by SandeepHar** [comment]
Ok Thanks im on it

**Comment by sdjali** [comment]
If you find any dificulty you can contact me at anytime

**Comment by SandeepHar** [comment]
I followed the procedure shown in video but my usb remain disable pc does't detect it

**Comment by sdjali** [comment]
I had the same problem before but first tell me you still can use the lan
cable .??

**Comment by SandeepHar** [comment]
yes i can

**Comment by SandeepHar** [comment]
Lan cable is working on it

**Comment by sdjali** [comment]
So first use putty to put it in the factory mode then downgrade it to the
version  21.316.01.DM2.....after that downgdare to universal version
21.300.01.....

**Comment by SandeepHar** [comment]
What will be the connection type , IP address and port in putty ??

**Comment by sdjali** [comment]
First if you are using win 7 you need one soft to enable it first then ip
is 192.168.8.1 port 23.   Telnet connection type

**Comment by SandeepHar** [comment]
No. it say network connection refused when i connect in puttty

**Comment by SandeepHar** [comment]
which soft needed to enable it i did't get it

**Comment by sdjali** [comment]
You got it ...when email refused to send ???

**Comment by SandeepHar** [comment]
can be talk on whatsapp or facebook of email

**Comment by SandeepHar** [comment]
sandeepharchand@hotmail.com

**Comment by SandeepHar** [comment]
What will be possible couse of disabling of usb??

**Comment by sdjali** [comment]
It is the protection in the soft version 21.316.....

**Comment by SandeepHar** [comment]
Any way to enable

**Comment by sdjali** [comment]
I told you yesterday you need to downgrade as I told you first to
21.316.DM2.... then to universal version 21.300.01...

**Comment by SandeepHar** [comment]
Can you provide the link for 21.316.DM2

**Comment by SandeepHar** [comment]
Sir, Device not accepting 21.316dm2 firmware also. Red light lit when flashing complete.

**Comment by SandeepHar** [comment]
I flashed through multicast

**Comment by 3lf007** [comment]
hello please provide link for 21.316.dm2 
 alchemistrxstore@gmail.com
thank you

**Comment by sdjali** [comment]
​
 B310s-927_UPDATE_21.316.01.DM2.1269.BIN
<https://drive.google.com/file/d/0B_wYjXPcTwMfN2Yxak1Ldm9oa28/view?usp=drive_web>
​

**Comment by SandeepHar** [comment]
Thanks alot. I successfully revived my device. Now i installed 21.321 firmware anyone know how to enable telnet mode in this firmware

**Comment by sdjali** [comment]
You didnt tell us how did you proceed

**Comment by 3lf007** [comment]
i seem to have bricked my device it doesn't come up again... please help

**Comment by sdjali** [comment]
hello just explain what do you have as problem and how you arrived to that
situation what you have done ??? your hardware your version ??then we try
to help you as we can

**Comment by 3lf007** [comment]
So i successfully loaded the firmware then I tried to change the dashboard and that's when my issue started.
My modem Huawei B310s-927 started showing just on light (power bulb) which refused to turn off ... i finally got it turn off now the modem has refused to come on

**Comment by sdjali** [comment]
can you connect it with usb and use emergengy mode ??

**Comment by SandeepHar** [comment]
Dear sdali as you told first i enabled telnet mode by using one soft( sw_enable_telnet_by_hassan) i putty i entered 192.168.8.1, then i sent AT^ SFM = 1 after this command my usb enabled. then i uploaded the 21.321 firmware my device revived now its accepting all the sims thanks for your help!!. But in 21.321 the usb again disabled i repeated same process to enable the telnet but in this firmware i did't get success. I suggest not to update 21.321 because it will disable your usb and will have no other way to enable

**Comment by 3lf007** [comment]
how do you enter emergency mode?

**Comment by SandeepHar** [comment]
@3lf007 which firmware you installed??

**Comment by 3lf007** [comment]
B310s-927_UPDATE_21.300.01.00.00.rar
