### ISSUE TITLE
patch loader for E5330bs-2

### ISSUE THREAD

**Issue by zubair3** [forth32/balongflash#19]
sir i have e5330bs-2 device
need patch loader file and any kind of solution for this device

**Comment by alyasashiq** [comment]
I have slution for e5330bs-2

**Comment by zubair3** [comment]
Sir please tell me or give files of e5330bs-2

**Comment by chipoza** [comment]
link>>>>
https://github.com/forth32/balong-usbdload/blob/master/usblsafe-5330bs.bin

**Comment by aalirazamanzoor** [comment]
telenor e8372h21.316.01.04.274  solution+reset
https://drive.google.com/file/d/0Bx5FFDeIQ2szX2RQTG9qNTdSRHc/view?usp=sharing
