### ISSUE TITLE
Откуда данные по протоколу?

### ISSUE THREAD

**Issue by mkwork** [forth32/balongflash#8]
Откуда сама спецификация по протокола берётся? Они вообще в открытом виде бывают?

**Comment by forth32** [comment]
Да нет конечно. Дизассемблировал сервер прошивки (huasweidload, входит в ramdisk2 линуксовых ядер) и разобрал протокол.

-- 
Alexander Stepanov

**Comment by mkwork** [comment]
Понял, спасибо. На такие подвиги я не горазд, надеялся до последнего что просто не нагуглил.
